# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# IMP_4_CREATE_TABLE_CALC.py
# Created on: 2013-10-11 14:41:28.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput = True

# Local variables:
Simpson_3_gdb = "\\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson_3.gdb"
IMPERVIOUS_AREA = "\\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson_3.gdb\\IMPERVIOUS_AREA"

# Process: Create Table
arcpy.CreateTable_management(Simpson_3_gdb, "IMPERVIOUS_AREA", "", "")

# Process: Add Field
arcpy.AddField_management(IMPERVIOUS_AREA, "PIN", "TEXT", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (2)
arcpy.AddField_management(IMPERVIOUS_AREA, "GPIN", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(IMPERVIOUS_AREA, "TOTAL_IMP_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (4)
arcpy.AddField_management(IMPERVIOUS_AREA, "STRUCTURE_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (5)
arcpy.AddField_management(IMPERVIOUS_AREA, "WALKWAY_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (10)
arcpy.AddField_management(IMPERVIOUS_AREA, "SIDEWALK_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (16)
arcpy.AddField_management(IMPERVIOUS_AREA, "DRIVEWAY_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (7)
arcpy.AddField_management(IMPERVIOUS_AREA, "ROAD_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (8)
arcpy.AddField_management(IMPERVIOUS_AREA, "PARKING_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (9)
arcpy.AddField_management(IMPERVIOUS_AREA, "MISC_STRUCT_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (6)
arcpy.AddField_management(IMPERVIOUS_AREA, "SLAB_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (6)
arcpy.AddField_management(IMPERVIOUS_AREA, "RAILROAD_AREA", "DOUBLE", "", "", "15", "", "NULLABLE", "NON_REQUIRED", "")

SDEoutPath = r"Database Connections\Connection to GISPRDDB.sde\cvGIS.CITY.IMPERVIOUS_AREA"

#arcpy.DeleteRows_management(SDEoutPath)

#arcpy.Append_management(IMPERVIOUS_AREA, SDEoutPath, 'NO_TEST')
