# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# IMP_2_INTERSECT.py
# Created on: 2013-10-11 10:17:55.00000
#   (generated by Mark Simpson)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#arcpy.env.workspace = "\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb"
arcpy.env.overwriteOutput = True

sde =  r"Database Connections\\CVGISWEB_Connection to GISPRDDB.sde"


# Local variables:
cvgis_CITY_vehicle_parking_area = sde + "\\cvgis.CITY.Transportation_Other\\cvgis.CITY.vehicle_parking_area"
cvgis_CITY_vehicle_driveway_area = sde + "\\cvgis.CITY.Transportation_Other\\cvgis.CITY.vehicle_driveway_area"
cvgis_CITY_road_area = sde + "\\cvgis.CITY.Transportation_Road\\cvgis.CITY.road_area_master"
cvgis_CITY_pedestrian_walkway_area = sde + "\\cvgis.CITY.Transportation_Other\\cvgis.CITY.pedestrian_walkway_area"
cvgis_CITY_structure_existing_area = sde + "\\cvgis.CITY.Buildings\\cvgis.CITY.structure_existing_area"
cvgis_CITY_miscellaneous_building_area = sde + "\\cvgis.CITY.Buildings\\cvgis.CITY.miscellaneous_building_area"
cvgis_CITY_slab_area = sde + "\\cvgis.CITY.Buildings\\cvgis.CITY.slab_area"
cvgis_CITY_parcel_area = sde + "\\cvgis.CITY.Cadastre\\cvgis.CITY.parcel_area"
cvgis_CITY_pedestrian_sidewalk_area = sde + "\\cvgis.CITY.Transportation_Other\\cvgis.CITY.pedestrian_sidewalk_area"
cvgis_CITY_railroad_area = sde + "\\cvgis.CITY.Transportation_Railroad\\cvgis.CITY.railroad_area"


intersect_slab_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_slab_1"
intersect_misc_struct_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_misc_struct_1"
intersect_walkway_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_walkway_1"
intersect_road_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_road_1"
intersect_driveway_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_driveway_1"
intersect_parking_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_parking_1"
intersect_structure_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_structure_1"
intersect_sidewalk_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_sidewalk_1"
intersect_railroad_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\intersect_railroad_1"


dissolve_slab_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_slab_1"
dissolve_misc_struct_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_misc_struct_1"
dissolve_walkway_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_walkway_1"
dissolve_road_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_road_1"
dissolve_driveway_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_driveway_1"
dissolve_parking_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_parking_1"
dissolve_structure_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_structure_1"
dissolve_sidewalk_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_sidewalk_1"
dissolve_railroad_1 = r"\\Metanoia\geodata\IT\SIMPSON\projects\Impervious\Simpson.gdb\dissolve_railroad_1"



# Process: Intersect slab
arcpy.Intersect_analysis([cvgis_CITY_slab_area, cvgis_CITY_parcel_area], intersect_slab_1)
# Process: Dissolve slab
arcpy.Dissolve_management(intersect_slab_1, dissolve_slab_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect misc buildings
arcpy.Intersect_analysis([cvgis_CITY_miscellaneous_building_area, cvgis_CITY_parcel_area], intersect_misc_struct_1)
# Process: Dissolve misc buildings
arcpy.Dissolve_management(intersect_misc_struct_1, dissolve_misc_struct_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect walkway
arcpy.Intersect_analysis([cvgis_CITY_pedestrian_walkway_area, cvgis_CITY_parcel_area], intersect_walkway_1)
# Process: Dissolve walkway
arcpy.Dissolve_management(intersect_walkway_1, dissolve_walkway_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect road_area
arcpy.Intersect_analysis([cvgis_CITY_road_area, cvgis_CITY_parcel_area], intersect_road_1)
# Process: Dissolve road_area
arcpy.Dissolve_management(intersect_road_1, dissolve_road_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect vehicle_driveway_area
arcpy.Intersect_analysis([cvgis_CITY_vehicle_driveway_area, cvgis_CITY_parcel_area], intersect_driveway_1)
# Process: Dissolve vehicle_driveway_area
arcpy.Dissolve_management(intersect_driveway_1, dissolve_driveway_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect vehicle_parking_area
arcpy.Intersect_analysis([cvgis_CITY_vehicle_parking_area, cvgis_CITY_parcel_area], intersect_parking_1)
# Process: Dissolve vehicle_parking_area
arcpy.Dissolve_management(intersect_parking_1, dissolve_parking_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect structure_existing_area
arcpy.Intersect_analysis([cvgis_CITY_structure_existing_area, cvgis_CITY_parcel_area], intersect_structure_1)
# Process: Dissolve structure_existing_area
arcpy.Dissolve_management(intersect_structure_1, dissolve_structure_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect pedestrian_sidewalk_area
arcpy.Intersect_analysis([cvgis_CITY_pedestrian_sidewalk_area, cvgis_CITY_parcel_area], intersect_sidewalk_1)
# Process: Dissolve pedestrian_sidewalk_area
arcpy.Dissolve_management(intersect_sidewalk_1, dissolve_sidewalk_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect railroad_area
arcpy.Intersect_analysis([cvgis_CITY_railroad_area, cvgis_CITY_parcel_area], intersect_railroad_1)
# Process: Dissolve railroad_area
arcpy.Dissolve_management(intersect_railroad_1, dissolve_railroad_1, ["GPIN"], "","MULTI_PART", "DISSOLVE_LINES")

