# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# IMP_2_INTERSECT.py
# Created on: 2013-10-11 10:17:55.00000
#   (generated by Mark Simpson)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

gdb = r'C:\Users\brownr\Desktop\imperv\data\imp.gdb'
arcpy.env.workspace = gdb
arcpy.env.overwriteOutput = True

sde = r'Database Connections\Connection to GISPRDDB direct connect.sde'

cvgis_CITY_parcel_area = sde + "\\cvgis.CITY.Cadastre\\cvgis.CITY.parcel_area"

imp_list = [
  sde+r'\cvgis.CITY.Buildings\cvgis.CITY.slab_area',
  sde+r'\cvgis.CITY.Buildings\cvgis.CITY.structure_existing_area',
  sde+r'\cvgis.CITY.Buildings\cvgis.CITY.miscellaneous_building_area',
  sde+r'\cvgis.CITY.Transportation_Other\cvgis.CITY.pedestrian_walkway_area',
  sde+r'\cvgis.CITY.Transportation_Railroad\cvgis.CITY.railroad_area',
  sde+r'\cvgis.CITY.Transportation_Other\cvgis.CITY.pedestrian_sidewalk_area',
  sde+r'\cvgis.CITY.Transportation_Road\cvgis.CITY.road_area_master',
  sde+r'\cvgis.CITY.Transportation_Other\cvgis.CITY.vehicle_driveway_area',
  sde+r'\cvgis.CITY.Transportation_Other\cvgis.CITY.vehicle_parking_area'
  ]

for feat in imp_list:
  inte = gdb + '\\' + feat.split('.')[-1] + '_int'
  dis = gdb + '\\' + feat.split('.')[-1] + '_dis'
  arcpy.Intersect_analysis([feat, cvgis_CITY_parcel_area], inte)
  arcpy.Dissolve_management(inte, dis, ["GPIN"], "","MULTI_PART", 
  "DISSOLVE_LINES")
